pull_request_rules:
  - name: automatic merge when CI passes and 1 reviews
    conditions:
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - base=main
      - label!=manual-merge
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
