pull_request_rules:
  - name: automatic merge when CI passes and 1 reviews
    conditions:
      - base=main
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
