[toolchain]
channel = "nightly-2024-03-11"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 3b1717c052de4a2dbdd3badb0e7a885f40a8ad9e

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
