[toolchain]
channel = "nightly-2023-02-01"
components = ["rust-src", "rustc-dev", "llvm-tools-preview"]
# commit_hash = dc1d9d50fba2f6a1ccab8748a0050cde38253f60

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change REQUIRED_TOOLCHAIN in crates/rustc_codegen_spirv/src/build.rs also.
