[toolchain]
channel = "nightly-2024-01-05"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = f688dd684faca5b31b156fac2c6e0ae81fc9bc90

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
