[toolchain]
channel = "nightly-2023-02-15"
components = ["rust-src", "rustc-dev", "llvm-tools-preview"]
# commit_hash = 0416b1a6f6d5c42696494e1a3a33580fd3f669d8

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change REQUIRED_TOOLCHAIN in crates/rustc_codegen_spirv/src/build.rs also.
