[toolchain]
channel = "nightly-2024-01-08"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 75c68cfd2b9870f2953b62d250bd7d0564a7b56d

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
