[toolchain]
channel = "nightly-2024-03-01"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 878c8a2a62d49ca5c454547ad67290a1df746cb5

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
