[toolchain]
channel = "nightly-2024-03-14"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 3cbb93223f33024db464a4df27a13c7cce870173

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
