[toolchain]
channel = "nightly-2023-11-26"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = f5dc2653fdd8b5d177b2ccbd84057954340a89fc

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
