[toolchain]
channel = "nightly-2024-04-01"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 805813650248c1a2f6f271460d728d1bb852d2a7

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
