[toolchain]
channel = "nightly-2024-02-01"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 11f32b73e0dc9287e305b5b9980d24aecdc8c17f

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
