[toolchain]
channel = "nightly-2024-03-21"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 1388d7a069d872bcfe5e5dd97ef61fa0a586fac0

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
