[toolchain]
channel = "nightly-2023-12-31"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 2a3e63551fe21458637480a97b65a2d15dec8062

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
