[toolchain]
channel = "nightly-2023-12-16"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = a96d57bdb6d2bb6d233d7d5aaefc2995ab99be01

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
