[toolchain]
channel = "nightly-2024-01-06"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 595bc6f00369475047538fdae1ff8cea692ac385

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
