[toolchain]
channel = "nightly-2023-09-30"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 8ce4540bd6fe7d58d4bc05f1b137d61937d3cf72

# Whenever changing the nightly channel, also update the commit hash above.
