[package]
name = "run-wasm"
description = "cargo-run-wasm helper/wrapper (see cargo-run-wasm docs)"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cargo-run-wasm = "0.3.2"
