[package]
name = "spirv-tools"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
edition = "2018"

[features]
opt = ["spirv-tools-sys/opt"]
val = ["spirv-tools-sys/val"]

[dependencies]
spirv-tools-sys = { path = "../spirv-tools-sys" }
