[package]
name = "build_libcore_test"
version = "0.1.0"
authors = ["Ashley Hauck <ashley.hauck@embark-studios.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { path = "../../spirv-std" }

[workspace]
